---
title: "Dashboard 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dygraphs)
```

Page 1
===
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Page 2
====
Column
-----------------------------------------------------------------------

### Chart A {data-height=200}

- point 1
- point 2
- point 3

### Chart B 
Text board

```{r}

```

Page 3 {data-icon="fa-table"}
===
Column {data-width=350}
-----------------------------------------------------------------------

### Chart D

```{r}

```

### Chart E

```{r}

```

### Chart F

```{r}

```

Page 4 {data-orientation=rows}
===
Row {data-height=650}
-------------------------------------
    
### Chart 1
    
```{r}

```
   
Row {data-height=350}
-------------------------------------
    
### Chart 2
    
```{r}

```
    
### Chart 3

```{r}

```

Page 5
===
Column{data-width=650}
---------------------------------------------------------------------

### Chart 1

```{r}

```

Column {data-width=350}
-------------------------------------
    
### Chart 2
    
```{r}

```
    
### Chart 3

```{r}

```
 
Page 6 {data-icon="fa-hashtag"}
===
Column {data-width=650, .tabset}
---------------------------------------------------------------------

### Chart 1

```{r}

```

### Chart 2

```{r}

```

### Chart 3

```{r}

```

Column {data-width=350, .tabset}
-------------------------------------
    
### Chart 4
    
```{r}

```
    
### Chart 5

```{r}

```


Page 7 {data-orientation=rows}
===
Row {data-height=650, .tabset}
---------------------------------------------------------------------

### Chart 1

```{r}

```

### Chart 2

```{r}

```

### Chart 3

```{r}

```

Row {data-height=350, .tabset}
-------------------------------------
    
### Chart 4
    
```{r}

```
    
### Chart 5

```{r}

```

Page 8 {data-orientation=rows}
===
Row
-----------------------------------------------------------------------

### Articles per Day

```{r}
valueBox(45, icon = "fa-pencil", href="#details")
```

### Comments per Day

```{r}
valueBox(126, icon = "fa-comments")
```

### Spam per Day

```{r}
spam <- 5
valueBox(spam, 
         icon = "fa-trash",
         color = ifelse(spam > 10, "warning", "primary"))
```


Page 11 {data-orientation=rows}
===
Row 
-------------------------------------
    
### Basic bar plot
    
```{r}
data(diamonds)
diamonds %>% 
  ggplot(aes(x = cut, y = mean(price), fill = cut)) +
  geom_bar(stat = "identity") +
  
  ggtitle("Basic Bar Plot") +
  xlab("CUT") +
  ylab("price") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```
   
Row {.tabset .tabset-fade}
-------------------------------------
   
### Stacked Bar plot

```{r}
diamonds %>% 
  ggplot(aes(x = cut, fill = clarity)) + # removed y argument and value
  geom_bar() +
  ggtitle("Stacked Bar Plot") +
  xlab("CUT") +
  ylab("COUNT") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```   
 
### Density plot
    
```{r}
ggplot(diamonds) +
  geom_density(aes(x = price, 
                   fill = cut), alpha = 0.7)+
  
  ggtitle("Density Plot") +
  xlab("price") +
  ylab("Density") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```

